version: '3'
services:
  cs:
    build: ./cs
    ports:
      - 5000:5000
    environment:
      - NUM_PROC=${NUM_PROC}
      - DES_ACCESSES=${DES_ACCESSES}
    
  
  master:
    build:
      context: ./
      dockerfile: ./master/Dockerfile
    environment:
      - NUM_PROC=${NUM_PROC}
      - EXP_TIME=${EXP_TIME}
      - AUTOMODE=${AUTOMODE}
      - LOAD=${LOAD}
      - PROTOCOL=${PROTOCOL}
      - CS_TIME=${CS_TIME}
    volumes:
      - "./data/automatic:/app/data"
    depends_on:
      - cs
  
  process:
    build:
      context: ./
      dockerfile: ./process/Dockerfile
    
    environment:
      - INDEX=${INDEX:-0}
      - NUM_PROC=${NUM_PROC}
      - PROTOCOL=${PROTOCOL}
      - CS_TIME=${CS_TIME}
      - AUTOMODE=${AUTOMODE}
    entrypoint: /app/entrypoint.sh
    depends_on:
      - master
    deploy:
      replicas: ${NUM_PROC}