version: '3'
services:
  cs:
    build: ./cs
    ports:
      - 5000:5000
    
  
  master:
    build:
      context: ./
      dockerfile: ./master/Dockerfile
    depends_on:
      - cs
  
  process:
    build:
      context: ./
      dockerfile: ./process/Dockerfile
    
    environment:
      - INDEX=${INDEX:-0}
    entrypoint: /app/entrypoint.sh
    depends_on:
      - master
    deploy:
      replicas: 3
